<a href="https://colab.research.google.com/github/Atay455/My_ML_Jorney_Projects/blob/main/Fake_News_Detection/Fake_News_Detection.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [62]:
import numpy as np
import pandas as pd
import re
import string
from sklearn.metrics import classification_report
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

In [63]:
import nltk
nltk.download("stopwords")

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [64]:
# Printing stopwords in english
print(stopwords.words("english"))

['a', 'about', 'above', 'after', 'again', 'against', 'ain', 'all', 'am', 'an', 'and', 'any', 'are', 'aren', "aren't", 'as', 'at', 'be', 'because', 'been', 'before', 'being', 'below', 'between', 'both', 'but', 'by', 'can', 'couldn', "couldn't", 'd', 'did', 'didn', "didn't", 'do', 'does', 'doesn', "doesn't", 'doing', 'don', "don't", 'down', 'during', 'each', 'few', 'for', 'from', 'further', 'had', 'hadn', "hadn't", 'has', 'hasn', "hasn't", 'have', 'haven', "haven't", 'having', 'he', "he'd", "he'll", 'her', 'here', 'hers', 'herself', "he's", 'him', 'himself', 'his', 'how', 'i', "i'd", 'if', "i'll", "i'm", 'in', 'into', 'is', 'isn', "isn't", 'it', "it'd", "it'll", "it's", 'its', 'itself', "i've", 'just', 'll', 'm', 'ma', 'me', 'mightn', "mightn't", 'more', 'most', 'mustn', "mustn't", 'my', 'myself', 'needn', "needn't", 'no', 'nor', 'not', 'now', 'o', 'of', 'off', 'on', 'once', 'only', 'or', 'other', 'our', 'ours', 'ourselves', 'out', 'over', 'own', 're', 's', 'same', 'shan', "shan't", 'she', "she'd", "she'll", "she's", 'should', 'shouldn', "shouldn't", "should've", 'so', 'some', 'such', 't', 'than', 'that', "that'll", 'the', 'their', 'theirs', 'them', 'themselves', 'then', 'there', 'these', 'they', "they'd", "they'll", "they're", "they've", 'this', 'those', 'through', 'to', 'too', 'under', 'until', 'up', 've', 'very', 'was', 'wasn', "wasn't", 'we', "we'd", "we'll", "we're", 'were', 'weren', "weren't", "we've", 'what', 'when', 'where', 'which', 'while', 'who', 'whom', 'why', 'will', 'with', 'won', "won't", 'wouldn', "wouldn't", 'y', 'you', "you'd", "you'll", 'your', "you're", 'yours', 'yourself', 'yourselves', "you've"]

**Data Pre-processing**

In [65]:
# loading the dataset to our pandas DataFrame
news_dataset_fake = pd.read_csv("Fake.csv")
news_dataset_true = pd.read_csv("True.csv")

In [66]:
news_dataset_fake["class"] = 0
news_dataset_true["class"] = 1

In [67]:
news_dataset_fake.head(10)

,title,text,subject,date,class
0,Donald Trump Sends Out Embarrassing New Year’...,Donald Trump just couldn t wish all Americans ...,News,"December 31, 2017",0
1,Drunk Bragging Trump Staffer Started Russian ...,House Intelligence Committee Chairman Devin Nu...,News,"December 31, 2017",0
2,Sheriff David Clarke Becomes An Internet Joke...,"On Friday, it was revealed that former Milwauk...",News,"December 30, 2017",0
3,Trump Is So Obsessed He Even Has Obama’s Name...,"On Christmas day, Donald Trump announced that ...",News,"December 29, 2017",0
4,Pope Francis Just Called Out Donald Trump Dur...,Pope Francis used his annual Christmas Day mes...,News,"December 25, 2017",0
5,Racist Alabama Cops Brutalize Black Boy While...,The number of cases of cops brutalizing and ki...,News,"December 25, 2017",0
6,"Fresh Off The Golf Course, Trump Lashes Out A...",Donald Trump spent a good portion of his day a...,News,"December 23, 2017",0
7,Trump Said Some INSANELY Racist Stuff Inside ...,In the wake of yet another court decision that...,News,"December 23, 2017",0
8,Former CIA Director Slams Trump Over UN Bully...,Many people have raised the alarm regarding th...,News,"December 22, 2017",0
9,WATCH: Brand-New Pro-Trump Ad Features So Muc...,Just when you might have thought we d get a br...,News,"December 21, 2017",0

In [68]:
news_dataset_true.head(10)

,title,text,subject,date,class
0,"As U.S. budget fight looms, Republicans flip t...",WASHINGTON (Reuters) - The head of a conservat...,politicsNews,"December 31, 2017",1
1,U.S. military to accept transgender recruits o...,WASHINGTON (Reuters) - Transgender people will...,politicsNews,"December 29, 2017",1
2,Senior U.S. Republican senator: 'Let Mr. Muell...,WASHINGTON (Reuters) - The special counsel inv...,politicsNews,"December 31, 2017",1
3,FBI Russia probe helped by Australian diplomat...,WASHINGTON (Reuters) - Trump campaign adviser ...,politicsNews,"December 30, 2017",1
4,Trump wants Postal Service to charge 'much mor...,SEATTLE/WASHINGTON (Reuters) - President Donal...,politicsNews,"December 29, 2017",1
5,"White House, Congress prepare for talks on spe...","WEST PALM BEACH, Fla./WASHINGTON (Reuters) - T...",politicsNews,"December 29, 2017",1
6,"Trump says Russia probe will be fair, but time...","WEST PALM BEACH, Fla (Reuters) - President Don...",politicsNews,"December 29, 2017",1
7,Factbox: Trump on Twitter (Dec 29) - Approval ...,The following statements were posted to the ve...,politicsNews,"December 29, 2017",1
8,Trump on Twitter (Dec 28) - Global Warming,The following statements were posted to the ve...,politicsNews,"December 29, 2017",1
9,Alabama official to certify Senator-elect Jone...,WASHINGTON (Reuters) - Alabama Secretary of St...,politicsNews,"December 28, 2017",1

In [69]:
news_dataset_fake.shape, news_dataset_true.shape

((23481, 5), (21417, 5))

In [111]:
df_fake_manual_testing = news_dataset_fake.tail(10)
df_true_manual_testing = news_dataset_true.tail(10)

In [112]:
news_dataset_fake = news_dataset_fake.iloc[:-10]
news_dataset_true = news_dataset_true.iloc[:-10]

In [113]:
data_manual_testing = pd.concat([df_fake_manual_testing, df_true_manual_testing], axis =0)
data_merge = pd.concat([news_dataset_fake,news_dataset_true],axis=0)

In [114]:
data_manual_testing.to_csv("manual_testing.csv")

In [115]:
data_merge.head(10)

,title,text,subject,date,class
0,Donald Trump Sends Out Embarrassing New Year’...,Donald Trump just couldn t wish all Americans ...,News,"December 31, 2017",0
1,Drunk Bragging Trump Staffer Started Russian ...,House Intelligence Committee Chairman Devin Nu...,News,"December 31, 2017",0
2,Sheriff David Clarke Becomes An Internet Joke...,"On Friday, it was revealed that former Milwauk...",News,"December 30, 2017",0
3,Trump Is So Obsessed He Even Has Obama’s Name...,"On Christmas day, Donald Trump announced that ...",News,"December 29, 2017",0
4,Pope Francis Just Called Out Donald Trump Dur...,Pope Francis used his annual Christmas Day mes...,News,"December 25, 2017",0
5,Racist Alabama Cops Brutalize Black Boy While...,The number of cases of cops brutalizing and ki...,News,"December 25, 2017",0
6,"Fresh Off The Golf Course, Trump Lashes Out A...",Donald Trump spent a good portion of his day a...,News,"December 23, 2017",0
7,Trump Said Some INSANELY Racist Stuff Inside ...,In the wake of yet another court decision that...,News,"December 23, 2017",0
8,Former CIA Director Slams Trump Over UN Bully...,Many people have raised the alarm regarding th...,News,"December 22, 2017",0
9,WATCH: Brand-New Pro-Trump Ad Features So Muc...,Just when you might have thought we d get a br...,News,"December 21, 2017",0

In [116]:
data_merge = data_merge.drop(["title", "subject", "date"], axis=1)
data_merge.head(10)

                                                text  class
0  Donald Trump just couldn t wish all Americans ...      0
1  House Intelligence Committee Chairman Devin Nu...      0
2  On Friday, it was revealed that former Milwauk...      0
3  On Christmas day, Donald Trump announced that ...      0
4  Pope Francis used his annual Christmas Day mes...      0
5  The number of cases of cops brutalizing and ki...      0
6  Donald Trump spent a good portion of his day a...      0
7  In the wake of yet another court decision that...      0
8  Many people have raised the alarm regarding th...      0
9  Just when you might have thought we d get a br...      0

In [117]:
data_merge = data_merge.sample(frac=1)

In [118]:
data_merge.head(10)

                                                    text  class
7657   If there s one person in this world that clear...      0
5835   TOKYO (Reuters) - Japan is hammering out plans...      1
8861   Conservatives alongside right-wing media outle...      0
2955   WASHINGTON (Reuters) - Spending on the Medicai...      1
22594  Special Report: Savvy neocons see Hillary Clin...      0
16575  BANGKOK (Reuters) - Somber crowds began gather...      1
18468  Talk about projecting! On Fareed Zakaria s CNN...      0
3278   OTTAWA (Reuters) - U.S. Treasury Secretary Ste...      1
22568  Tune in to the Alternate Current Radio Network...      0
11983  SANTIAGO (Reuters) - Billionaire conservative ...      1

In [119]:
data_merge.isnull().sum()

text     0
class    0
dtype: int64

In [120]:
def word_drop(text):
  text = text.lower()
  text = re.sub(r'\[.*?\]','',text)
  text = re.sub(r"\\W"," ",text)
  text = re.sub(r'https?://\S+|www\/S+','',text)
  text = re.sub(r'<.*?>+','',text)
  text = re.sub(r'[%s]'% re.escape(string.punctuation),'',text)
  text = re.sub(r'\n','',text)
  text = re.sub(r'\w*\d\w*','',text)
  return text

In [121]:
data_merge["text"] = data_merge["text"].apply(word_drop)

In [122]:
data_merge.head(10)

                                                    text  class
7657   if there s one person in this world that clear...      0
5835   tokyo reuters  japan is hammering out plans to...      1
8861   conservatives alongside rightwing media outlet...      0
2955   washington reuters  spending on the medicaid h...      1
22594  special report savvy neocons see hillary clint...      0
16575  bangkok reuters  somber crowds began gathering...      1
18468  talk about projecting on fareed zakaria s cnn ...      0
3278   ottawa reuters  us treasury secretary steven m...      1
22568  tune in to the alternate current radio network...      0
11983  santiago reuters  billionaire conservative seb...      1

In [123]:
x = data_merge["text"]
y = data_merge["class"]

In [125]:
x_train, x_test,y_train,y_test = train_test_split(x,y ,test_size = 0.25)

In [126]:
vectorization = TfidfVectorizer()
xv_train = vectorization.fit_transform(x_train)
xv_test = vectorization.transform(x_test)

### Logistic Regression

In [129]:
LR = LogisticRegression()
LR.fit(xv_train,y_train)

LogisticRegression()

In [130]:
LR.score(xv_test,y_test)

0.985109228711547

In [131]:
predict_LR = LR.predict(xv_test)

In [132]:
print(classification_report(y_test,predict_LR))

              precision    recall  f1-score   support

           0       0.99      0.99      0.99      5846
           1       0.98      0.98      0.98      5369

    accuracy                           0.99     11215
   macro avg       0.99      0.99      0.99     11215
weighted avg       0.99      0.99      0.99     11215

### Decision Tree Classification

In [134]:
from sklearn.tree import DecisionTreeClassifier

In [138]:
DT = DecisionTreeClassifier()
DT.fit(xv_train,y_train)

DecisionTreeClassifier()

In [139]:
DT.score(xv_test,y_test)

0.9958091841283995

In [141]:
pred_DT = DT.predict(xv_test)

In [143]:
print(classification_report(y_test,pred_DT))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00      5846
           1       0.99      1.00      1.00      5369

    accuracy                           1.00     11215
   macro avg       1.00      1.00      1.00     11215
weighted avg       1.00      1.00      1.00     11215

### Gradient Boosting Classifier

In [146]:
from sklearn.ensemble import GradientBoostingClassifier

In [147]:
GBC = GradientBoostingClassifier(random_state=0)
GBC.fit(xv_train,y_train)

GradientBoostingClassifier(random_state=0)

In [ ]:
GBC.score(xv_test,y_test)

In [ ]:
pred_GBC = GBC.predict(xv_test)

In [ ]:
print(classification_report)

### Random Forest Classifier

In [148]:
from sklearn.ensemble import RandomForestClassifier

In [149]:
RFC = RandomForestClassifier(random_state=0)
RFC.fit(xv_train,y_train)

RandomForestClassifier(random_state=0)

In [150]:
RFC.score(xv_test,y_test)

0.9866250557289344

In [151]:
pred_RFC = RFC.predict(xv_test)

In [153]:
print(classification_report(y_test,pred_RFC))

              precision    recall  f1-score   support

           0       0.99      0.99      0.99      5846
           1       0.99      0.99      0.99      5369

    accuracy                           0.99     11215
   macro avg       0.99      0.99      0.99     11215
weighted avg       0.99      0.99      0.99     11215

**Manual Testing**

In [161]:
def output_label(n):
    if n == 0:
        return "Fake News"
    elif n == 1:
        return "Not A Fake News"


def manual_testing(news):
    # Put the news text into a dictionary
    testing_news = {"text": [news]}

    # Convert dictionary to DataFrame
    new_def_test = pd.DataFrame(testing_news)

    # Apply text preprocessing
    new_def_test["text"] = new_def_test["text"].apply(word_drop)

    # Extract text column
    new_x_test = new_def_test["text"]

    # Convert text into numerical vectors
    new_xv_test = vectorization.transform(new_x_test)

    # Predictions from different models
    pred_LR = LR.predict(new_xv_test)
    pred_DT = DT.predict(new_xv_test)
    pred_GBC = GBC.predict(new_xv_test)
    pred_RFC = RFC.predict(new_xv_test)

    # Print predictions
    print(
        "\n\nLR Prediction: {} \nDT Prediction: {} \nGBC Prediction: {} \nRFC Prediction: {}".format(
            output_label(pred_LR[0]),
            output_label(pred_DT[0]),
            output_label(pred_GBC[0]),
            output_label(pred_RFC[0])
        )
    )

In [162]:
news = str(input())
manual_testing(news)

21st Century Wire says This week, the historic international Iranian Nuclear Deal was punctuated by a two-way prisoner swap between Washington and Tehran, but it didn t end quite the way everyone expected. On the Iranian side, one of the U.S. citizens who was detained in Iran, Nosratollah Khosravi-Roodsari, has stayed in Iran, but on the U.S. side   all 7 of the Iranians held in U.S. prisons DID NOT show up to their flight to Geneva for the prisoner exchange   with at least 3 electing to stay in the U.S  TEHRAN SIDE: In Iran, 5 U.S. prisoners were released, with 4 of them making their way to Germany via Switzerland.Will Robinson Daily MailNone of the Iranians freed in the prisoner swap have returned home and could still be in the United States, it has been reported.The seven former inmates, who were released as part of a deal with the Islamic republic, did not show up to get a flight to Geneva, Switzerland, where the exchange was set to take place on Sunday.Three of the Iranians have decided to stay in the United States, ABC reported, with some moving in with their families. However it is not known where the other four are.Three of the Americans who had been detained in Iran   Washington Post journalist Jason Rezaian, former U.S. Marine Amir Hekmati and Christian pastor Saeed Abedini   left Tehran at around 7am the same day, but weren t met by their counterparts in Switzerland Continue this story at the Mail OnlineREAD MORE IRAN NEWS AT: 21st Century Wire Iran Files


LR Prediction: Fake News
DT Prediction: Fake News
GBC Prediction: Fake News
RFC Prediction: Fake News